spring.application.name=EcoRecicla_backend
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/BD_EcoRecicla
spring.datasource.username=postgres
spring.datasource.password=1234
server.port=8080